
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

bind r source-file ~/.tmux.conf

# Set vi key bindings mode
set -g mode-keys vi
set -g status-keys vi

set-option -g allow-rename off
set -g base-index 1
setw -g pane-base-index 1

# Custom Colors the cheap and easy way
set-option -g status-position top
set -g window-status-current-style 'fg=colour233 bg=colour8 bold'
set -g status-justify left
set -g status-style 'bg=colour8 fg=colour233 dim'
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour8] %Y-%d-%m #[fg=colour233,bg=colour8] %H:%M'
set -g status-right-length 50
set -g status-left-length 20

# references: 
#  https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
